### ISSUE TITLE
type check incorrect

### ISSUE THREAD

**Issue by markussieber** [sengaya/libkeepalive#1]
hi

there is a problem in the type check of the socket type. Since linux 2.6.27  the type can also contain some criteria which are bitwise ORed. These break the if statement as shown below:

socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 7

fails to match

```
if((domain == PF_INET) && (type == SOCK_STREAM)) {
```

the check should be
    if((domain == PF_INET) && (type | SOCK_STREAM)) {

Markus

**Comment by sengaya** [comment]
Thanks for the report. As I only provide the debian package and I'm not affiliated with upstream, I recommend to contact the upstream author Fabio Busatto (see README for details).
